#!/bin/sh -x
cd $QTDIR/demos/browser
for sha in `git log --after=04/11/2008 --pretty=format:%H .`; do git format-patch --relative --src-prefix="a/src/" --dst-prefix="b/src/" -k $sha~1..$sha; done
cd -
mv $QTDIR/demos/browser/00* .
for file in `ls 00*`; do git am -3 -k $file; done

